from __future__ import annotations

import argparse
import json
from pathlib import Path
import shlex
import sys


ROOT = Path(__file__).resolve().parents[1]
WEB_ROOT = ROOT / "web"
PACKAGE_PATH = WEB_ROOT / "package.json"
GENERATED_ROOT = WEB_ROOT / "src" / "generated"
GENERATED_MARKER = (
    "This file was automatically generated by json-schema-to-typescript."
)


class GeneratedWebTypeError(ValueError):
    """Raised when browser protocol bindings lose their canonical owner."""


def _generation_pairs(command: str) -> tuple[tuple[Path, Path], ...]:
    pairs: list[tuple[Path, Path]] = []
    for segment in command.split("&&"):
        arguments = shlex.split(segment.strip(), posix=True)
        if not arguments:
            continue
        if arguments[0] != "json2ts":
            raise GeneratedWebTypeError(
                "web generate:types may contain only json2ts commands"
            )
        try:
            source = Path(arguments[arguments.index("-i") + 1])
            output = Path(arguments[arguments.index("-o") + 1])
        except (IndexError, ValueError) as exc:
            raise GeneratedWebTypeError(
                "every json2ts command requires one -i source and -o output"
            ) from exc
        pairs.append((source, output))
    if not pairs:
        raise GeneratedWebTypeError("web generate:types has no json2ts outputs")
    return tuple(pairs)


def validate() -> dict[str, object]:
    package = json.loads(PACKAGE_PATH.read_text(encoding="utf-8"))
    command = package.get("scripts", {}).get("generate:types")
    if not isinstance(command, str) or not command.strip():
        raise GeneratedWebTypeError("web package has no generate:types command")
    pairs = _generation_pairs(command)
    declared_outputs: set[str] = set()
    sources: set[str] = set()
    root = ROOT.resolve()
    for source, output in pairs:
        source_path = (WEB_ROOT / source).resolve()
        output_path = (WEB_ROOT / output).resolve()
        try:
            source_relative = source_path.relative_to(root).as_posix()
            output_relative = output_path.relative_to(root).as_posix()
        except ValueError as exc:
            raise GeneratedWebTypeError(
                "generate:types source or output escapes the repository"
            ) from exc
        if not source_path.is_file():
            raise GeneratedWebTypeError(
                f"generate:types source does not exist: {source_relative}"
            )
        if not output_path.is_file():
            raise GeneratedWebTypeError(
                f"generate:types output does not exist: {output_relative}"
            )
        prefix = output_path.read_text(encoding="utf-8")[:512]
        if GENERATED_MARKER not in prefix:
            raise GeneratedWebTypeError(
                f"generate:types output lacks its generator marker: {output_relative}"
            )
        sources.add(source_relative)
        declared_outputs.add(output_relative)

    if len(declared_outputs) != len(pairs):
        raise GeneratedWebTypeError(
            "web generate:types declares a duplicate output"
        )

    marked_outputs = {
        path.relative_to(ROOT).as_posix()
        for path in GENERATED_ROOT.glob("*.ts")
        if GENERATED_MARKER in path.read_text(encoding="utf-8")[:512]
    }
    if declared_outputs != marked_outputs:
        raise GeneratedWebTypeError(
            "web generate:types outputs do not match generated TypeScript markers: "
            f"declared={sorted(declared_outputs)}, marked={sorted(marked_outputs)}"
        )
    return {
        "ok": True,
        "sources": sorted(sources),
        "outputs": sorted(declared_outputs),
    }


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Validate canonical browser protocol type generation"
    )
    parser.add_argument("--check", action="store_true", required=True)
    parser.parse_args()
    print(json.dumps(validate(), indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (GeneratedWebTypeError, OSError, ValueError) as exc:
        print(f"generated browser type validation failed: {exc}", file=sys.stderr)
        raise SystemExit(1)
